# name: Deploy to AWS ECR and Update SageMaker

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: eu-north-1

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build, Tag, and Push Image to ECR
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: new-repo-movie
#           IMAGE_TAG: latest
#         run: |
#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

name: Deploy Hospital AI to SageMaker

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/new-repo-movie:latest

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to SageMaker
        run: |

          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/new-repo-movie:latest

          TIME=$(date +%s)

          MODEL_NAME="hospital-model-$TIME"
          CONFIG_NAME="hospital-config-$TIME"
          ENDPOINT_NAME="hospital-endpoint"

          echo "Deleting old endpoint if exists..."

          aws sagemaker delete-endpoint \
            --endpoint-name $ENDPOINT_NAME || true

          sleep 40

          echo "Creating model..."

          aws sagemaker create-model \
            --model-name $MODEL_NAME \
            --execution-role-arn "${{ secrets.SAGEMAKER_ROLE }}" \
            --primary-container Image=$IMAGE_URI,Environment="{GROQ_API_KEY=${{ secrets.GROQ_API_KEY }},ACCOUNT_SID=${{ secrets.ACCOUNT_SID }},AUTH_TOKEN=${{ secrets.AUTH_TOKEN }},TWILIO_NUMBER=${{ secrets.TWILIO_NUMBER }},MY_NUMBER=${{ secrets.MY_NUMBER }},BASE_URL=${{ secrets.BASE_URL }}}"

          echo "Creating endpoint config..."

          aws sagemaker create-endpoint-config \
            --endpoint-config-name $CONFIG_NAME \
            --production-variants VariantName=AllTraffic,ModelName=$MODEL_NAME,InitialInstanceCount=1,InstanceType=ml.m5.large

          echo "Creating endpoint..."

          aws sagemaker create-endpoint \
            --endpoint-name $ENDPOINT_NAME \
            --endpoint-config-name $CONFIG_NAME

          echo "Waiting for endpoint..."

          aws sagemaker wait endpoint-in-service \
            --endpoint-name $ENDPOINT_NAME

          echo "Deployment Successful"